version: "3"

services:
  csvserver:
    volumes:
     - ./inputFile:/csvserver/inputdata
    ports:
      - "9393:9300"
    image: infracloudio/csvserver
    environment:
      - CSVSERVER_BORDER=Orange



